name: ia_central
description: "Directorio de herramientas de IA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/imagenicono.png"
  adaptive_icon_background: "#0066FF"
  adaptive_icon_foreground: "assets/images/imagenicono.png"

flutter_native_splash:
  color: "#0066FF"
  image: "assets/images/imagenicono.png"
  android: true
  ios: true
  fullscreen: true
  color_dark: "#1A1F3A"
  image_dark: "assets/images/imagenicono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/